config/routes.rb
Rails.application.routes.draw do
  root to: 'tasks#index'
  get 'tasks/index', to: 'tasks#index'

  resources :tasks, only:[:index, :new, :create, :edit, :show]
  #get "/tasks/:id", to: 'tasks#show'
  #post "/tasks/new", to: 'tasks#new'
  post "/task/finished/:id", to: 'tasks#finished', as: :finished_path

  devise_for :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #root routes
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception

	before_action :configure_permitted_parameters, if: :devise_controller?

	protected

    	def configure_permitted_parameters
        	devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:firstName, :lastName, :email, :password, :password_confirmation)}

        	devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:firstName, :lastName, :email, :password, :password_confirmation, :current_password)}
    	end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!, only: [:new,:show,:finished] 
  
  def index
  	if (user_signed_in?)
  		@tasks = Task.where("user_id = ?", current_user.id)
  		@tasksToday = Task.where('task_date = ? and task_status = ? and user_id = ?', Date.today, "not finished", current_user.id)
  		#render plain: @tasksToday.inspect
  	end
  end

  def new

  end

  def show
  	if(current_user.id.to_s)
  		@task = Task.find_by(id: params[:id],user_id: current_user.id.to_s)
  	else
  		redirect_to action: "index"
  	end
  end

  def finished
  	@task = Task.find_by(id: params[:id])
  	if (@task.update(task_status: 'finished'))
  		redirect_to action: "index"
  	end
  end

  def create
  	@task = Task.new(task_params)
  	@task.save
  	redirect_to action: "index"
  end

  private
  	def task_params
  		params.require(:task).permit(:taskName,:task_date,:taskPriority,:task_status,:user_id,:description)
  	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/layouts/_alerts.html.erb
<p class="text-center alerts"><%= alert %></p>

app/views/layouts/_navbar.html.haml
%nav{:class => "navbar navbar-dark bg-dark"}
	.container.d-flex.justify-content-between

		%a{:class => "navbar-brand", :href => "../"}
			%img{:src => asset_path('logo.png'), :width => "115", :height => "32", :class => "d-inline-bl"}
		- if !user_signed_in? 
			= link_to('Sign in', new_user_session_path, class: "btn btn-outline-light btn-signin", role:"button")
		- else
			= link_to('Sign out', destroy_user_session_path, method: :delete, class: "btn btn-outline-light btn-signout", role:"button")

app/views/layouts/_notice.html.erb
<p class="text-center notices"><%= notice %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Turboly</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!--FONT-->
    <%= stylesheet_link_tag 'https://fonts.googleapis.com/css?family=Montserrat:400,700'%>
    <%= stylesheet_link_tag 'https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic'%>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
    

  </body>
</html>

app/views/tasks/index.html.haml
- if !user_signed_in? 
	.container-fluid
		.row
			.jumbotron.jumbotron-fluid.col-md-12
				.header-wrapper
					%h1{:class => "display-3 text-center font-weight-bold"} Welcome, new user !
					%p{:class => "lead text-center"} You may sign in or sign up before you can access your dashboard content
					.btn-home-wrapper.text-center
						%p{:class => "lead"}
							= link_to('Sign up', new_user_registration_path, class: "btn btn-success btn-lg btn-signup", role:"button")
- else	
	.container-fluid
		.row
			.col-md-10.col-sm-12.col-lg-10.mx-auto
				.card.card-form
					.card-body
						%h5.text-center 
							Welcome 
							= current_user.firstName
							this is your task
						%hr
						%table.table.table-striped.table-bordered{:id => "myTasks"}
							%thead
								%tr
									%td number
									%td task name
									%td date
									%td description
									%td priority
									%td action
							%tbody
								- ctr = 1
								- @tasks.each do |task|
									%tr
										%td
											= ctr
										%td
											= task.taskName
										%td
											= task.task_date
										%td
											= task.description
										%td
											= task.taskPriority
										%td
											= link_to('Details', task_path(id: task.id),class: "btn btn-info btn-block", role:"button")
											- if(task.task_status.to_s == "not finished")
												= link_to('Mark as finished', finished_path_url(id: task.id), method: :post, data: { confirm: "Are you sure its finished ?"},class: "btn btn-success btn-block", role:"button")
									- ctr = ctr + 1
						%br	
						= link_to('New Task', new_task_path,class: "btn btn-primary", role:"button")
	- if(@tasksToday.exists?)
		.modal.fade{:id => "tasksToday"}
			.modal-dialog.modal-lg
				.modal-content
					.modal-header
						= image_tag("warning.png", class: "rounded mx-auto d-block")
					.modal-body
						%h5.text-center Your task today
						%br
						%table.table.table-striped.table-bordered
							%thead
								%tr
									%td Number
									%td Task Name
									%td Priority
							%tbody
								- ctr = 1
								- @tasksToday.each do |taskToday|
									%tr
										%td
											= ctr
										%td
											= taskToday.taskName
										%td
											- if(taskToday.taskPriority == "1")
												.progress
													.progress-bar.progress-bar-striped.bg-success{ :style => "width: 25%"}
											- elsif(taskToday.taskPriority == "2")
												.progress
													.progress-bar.progress-bar-striped.bg-warning{ :style => "width: 50%"}
											- elsif(taskToday.taskPriority == "3")
												.progress
													.progress-bar.progress-bar-striped.bg-danger{ :style => "width: 100%"}
									- ctr = ctr + 1

app/views/tasks/new.html.haml
.container-fluid
    .row
        .col-md-4.col-sm-12.col-lg-4.mx-auto
            .card.card-form
                .card-body
                    = image_tag("add-task-icon.png", class: "rounded mx-auto d-block")
                    %hr
                    = form_with scope: :task, url: tasks_path, local: true do |f| 
                        .form-group
                            = f.text_field :taskName, autofocus: true, class: "form-control", placeholder: "Enter your task name", required: true
                        .form-group
                            = f.date_field :task_date, autofocus: true, class: "form-control", placeholder: "Enter your task date", min: Date.today, required: true
                        .form-group
                            = f.select :taskPriority, [['High', 3],['Medium', 2],['Low', 1]], {}, {:class => "form-control"}
                        .form-group
                            = f.text_area :description, class: "form-control", placeholder: "Enter your task description", rows: "4"
                        .form-group
                            = f.text_field :task_status, class: "form-control", value: "not finished", readonly: true
                        .form-group
                            = f.hidden_field :user_id, value: current_user.id
                        %hr
                        = f.submit "Submit Task", class: "btn btn-primary btn-block"

                  

app/views/tasks/show.html.haml
.container-fluid
	.row
		.col-md-6.col-sm-12.col-lg-6.mx-auto
			.card.card-form
				.card-body
					= image_tag("task-icon.png", class: "rounded mx-auto d-block")
					%br
					- if(@task)
						%h4.text-center.text-capitalize
							= @task.taskName
						%hr
						%dl.row
							%dt.col-md-6 Task Date: 
							%dd.col-md-6 
								= @task.task_date
							%dt.col-md-6 Task Priority: 
							%dd.col-md-6
								- if(@task.taskPriority == "1")
									.progress
										.progress-bar.progress-bar-striped.bg-success{ :style => "width: 25%"}
								- elsif(@task.taskPriority == "2")
									.progress
										.progress-bar.progress-bar-striped.bg-warning{ :style => "width: 50%"}
								- elsif(@task.taskPriority == "3")
									.progress
										.progress-bar.progress-bar-striped.bg-danger{ :style => "width: 100%"}
							%dt.col-md-6 Task Status: 
							%dd.col-md-6 
								= @task.task_status
						%hr
						%dl.row
							%dt.col-md-6 Task Descriptions:
							%dd.col-md-6
								= @task.description
						- if(@task.task_status.to_s == "not finished")
							%hr
							= link_to('Mark as finished', finished_path_url(id: @task.id), method: :post, data: { confirm: "Are you sure its finished ?"},class: "btn btn-primary btn-block", role:"button")
					- else
						%h3.text-center this task its not yours !